// src/components/pomodoro/Pomodoro.tsx
import { FC } from "react"
import { observer } from "mobx-react-lite"
import { PomodoroState as State } from "./PomodoroState"
import { PomodoroTimer } from "./PomodoroTimer"
import { PomodoroHeader } from "./PomodoroHeader"
import { PomodoroFooter } from "./PomodoroFooter"
import Head from "next/head"

export const Pomodoro: FC<{ state: State }> = observer(({ state }) => (
  <div className="flex h-screen w-screen flex-col items-center bg-focus-400 text-focus-100">
    <Head>
      {state.isStarted && <title>{`🍅 ${state.formatTime()}`}</title>}
      <meta name="theme-color" content={state.themeColor} />
    </Head>

    <PomodoroHeader state={state} />

    <div className="h-full w-full px-4 py-8 sm:max-w-lg md:max-w-xl">
      <PomodoroTimer state={state} />
    </div>

    <PomodoroFooter state={state} />
  </div>
))

// src/pages/pomodoro/Pomodoro.vue
<script setup lang="ts">
import { reactive } from "vue"
import { PomodoroState as State } from "./PomodoroState"
import PomodoroTimer from "./PomodoroTimer.vue"

const state = reactive(new State())
</script>

<template>
  <div class="h-screen w-screen bg-red-400 text-white">
    <div class="h-full flex flex-col justify-center items-center">
      <PomodoroTimer :state="state" />
    </div>
  </div>
</template>
