// components/pomodoro/PomodoroTimer.tsx
import * as React from "react"
import { PomodoroState as State } from "./PomodoroState"
import { observer } from "mobx-react-lite"

export const PomodoroTimer: React.FC<{ state: State }> = observer(
  ({ state }) => (
    <div className="text-9xl">
      {state.formatMinutes()}:{state.formatSeconds()}
    </div>
  )
)

// src/pages/pomodoro/PomodoroTimer.vue
<script setup lang="ts">
import type { PomodoroState as State } from "./PomodoroState"
import { onMounted } from "vue"

const props = defineProps<{ state: State }>()
const { state } = props

onMounted(() => {
  state.start()
})
</script>

<template>
  <div class="text-9xl">
    {{ state.formatMinutes() }}:{{ state.formatSeconds() }}
  </div>
</template>
